### PR TITLE
Trying to integrate Creality's "melzi" board from Ender 3

### PR DESCRIPTION
**Pull request by bfcoursewool**
When I flash this to the board it runs but the selector wheel/potentiometer on my LCD is not really working correctly... the selected menu item typically just jumps from the first to the last and generally doesn't very much respond to the knob turning. Sometimes it bounces around from one option to another, but it's pretty random and just as often it doesn't respond to turning the knob in any way. Clicking the knob does work at least. If I flash Marlin firmware onto the same board, with the same LCD, the selector knob scrolls through those menus exactly as expected, so at least I know it *can* work...

### CODE REVIEW

**Comment by i-make-robots** [comment]
I think configure.h is missing 

#define BOARD_MELZI 7  // Creality Melzi (Ender 3)

I mean, I don't see where BOARD_MELZI is defined.

**Comment by i-make-robots** [comment]
Also please PR to the dev branch.

**Comment by i-make-robots** [comment]
making "everything else" use Timer3 is genius.  so obviously more correct than what I had left in there.  Nice!
cAsInG on the includes also a nice catch.

**Comment by i-make-robots** [comment]
Hey.... not to be difficult but I updated the configuration.h with some improvements and updated the post on marginallyclever.com.  You did everything right with the information you had!  😅  I have tried to make it more clear going forward, like "please write your code (and pull requestion) on the dev branch".  Thank you for making things better! :)

**Comment by bfcoursewool** [comment]
Oh whoops yeah I had that define in the original clone I made but then when I forked it and copied my changes over for this PR I didn't include that bit. I'll fix and re-request on the dev branch :)

**Pull request closed without merging**
