### PR TITLE
PIO and ArduinoIDE compiling with the possibility to have more than one environment

### PR DESCRIPTION
**Pull request by captFuture**
Your base project is compiling on Arduino ide and Platformio with these changes 
- The libraries for arduino ide are in a .rar file because platformio ist pulling these automatically and if they are in the libraries folder it does not work
- I added a configs folder where multiple config files can reside (based on the board used)
- the build_flags in the configurations tell the compiler which config to use 
- the preprocessor checks if it is compiled with platformio otherwise the standard local_config.h method is used
- the folder for source files is changed to Makelangelo-firmware for compatibility with Arduino IDE folder structure needs

For platformio just a project needs to be set up and instead of the /src folder the Makelangelo-firmware can be cloned in.
A platformio.ini needs to be created...

my current platformio ini:

[platformio]
src_dir = Makelangelo-firmware

[env]
monitor_speed = 57600

[env:rumba]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = 
    -DHEADER_RUMBA
    -DPIO
lib_deps = SdFat, TMC2130Stepper, TMCStepper, U8g2, U8Glib, bitbucket-fmalpartida/LiquidCrystal @ 1.5.0

[env:ramps]
platform = atmelavr
board = megaatmega2560
framework = arduino
build_flags = 
    -DHEADER_RAMPS
    -DPIO
lib_deps = SdFat, TMC2130Stepper, TMCStepper, U8g2, U8Glib, bitbucket-fmalpartida/LiquidCrystal @ 1.5.0

### CODE REVIEW

**Comment by i-make-robots** [comment]
I guess I better install platformio and see if this works or not.  ...but then maybe its time to move everything to platformio?

**Comment by i-make-robots** [comment]
What's M5Stack?

**Comment by captFuture** [comment]
https://m5stack.com/collections/m5-core/products/grey-development-core

A modular STEM kit with an esp32, LCD Display, buttons and a SD card reader builtin. I am looking forward to port makelangelo there for modularity and a nice look :)
Currently I am soldering a pluggable stepper driver board for it because the one they sell is not usable for this application. (it has grbl on it and a mcu on its own)

**Comment by captFuture** [comment]
Not necessary any more because @cad435 has done a platformio tree

**Pull request closed without merging**
