### PR TITLE
Add motor sleep on timeout

### PR DESCRIPTION
**Pull request by mbells**
To help prevent stepper motors from overheating, disengage these
after not receiving a command for a while.

### CODE REVIEW

**Comment by i-make-robots** [comment]
Disengage (m18) already exists.

**Comment by mbells** [comment]
Thanks for your prompt response, Dan. I'm already aware of M18. The problem that this change is trying to solve is when the USB cord gets pulled but not the power, or something happens to the host computer and communication. Then the M18 command can't be received. The host software is setup so that the operator has to remember and manually issue the command. Having a reasonable timeout to shut down the motors helps prevent these from overheating.

BTW, i also have some fixes to the stepper code to make it go much faster and more smoothly. I see you did a bunch of fixes to the firmware over the summer since we originally got the code. I'm still testing these changes, though. I'm working with a couple others on this at a makerspace in Kitchener, Canada... we are over-driving the steppers to maximize the speed, but these will overheat if left on.

**Comment by i-make-robots** [comment]
Aha...  Well, theres' the TIMEOUT_OK delay.  You could have a second time that says 

if( DISABLE_TIMER expired ) M18();

or something to that effect.  DISABLE_TIMER might be 5x TIMEOUT_OK?

**Comment by i-make-robots** [comment]
Oh, and that's exactly what you cover.  Cool.

**Comment by i-make-robots** [comment]
How did you get around the i2c bottleneck of the AMS shields?

**Comment by i-make-robots** [comment]
Have you got a homepage?  I want put a thanks in the next update release notes.

**Comment by mbells** [comment]
Sorry, i've been on vacation this past week and missed the notifications. Here's the responses:

> How did you get around the i2c bottleneck of the AMS shields?

The original AMS shield doesn't use i2c. It writes directly to the a shift register and pwms the power for the active phase.

> Have you got a homepage?

http://mbells.ca/blog/

**Comment by i-make-robots** [comment]
Yes, you're right. How did you make it go faster?

**Pull request merged**
