### PR TITLE
Fix motor timing.

### PR DESCRIPTION
**Pull request by mbells**
Hi Dan,

You were wondering how i fixed the motors. I finally got to rebasing the code and testing it. I noted you copied AFMotorDrawbot but didn't delete the original... i didn't know which you wanted to keep, so i picked one (the original). A similar directory structure is used for Adafruit_MotorShield, so i'm not sure what was wrong with the old one... I can easily enough rebase if you delete one of the sets of files. Some of the diff is simply returning the code to more similar to the original AF code.

Code is using half stepping, so the correct value or MICROSTEPS is 2
rather than 16.
Time delay is now measured in us, not ms.
Provide a precise delay function.
Update some of the Adafruit code with the fixes that have been applied
since it was forked.
Remove steppingcounter, which was not sufficiently precise.
Add delays to the motor test g-codes... otherwise, the motors buzz but don't turn.

### CODE REVIEW

**Comment by i-make-robots** [comment]
the library files were moved to the root folder because arduino #include command was broken for several editions and it made life easier.  Can you please put them in the same place?  then I'll see the diff instead of "everything green and new!"

**Comment by i-make-robots** [comment]
Any chance of that update I requested?

**Comment by mbells** [comment]
I've updated it. I have a compile conflict keeping both versions of AFMotorDrawbot, so i removed the other one. I double checked and both are present on the master branch of your github repo.

**Comment by i-make-robots** [comment]
Ok... apparently I forgot about this PR and didn't notice it was still open until just now.  I am deeply embarrassed.

The current AMS support for Makelangelo is in https://github.com/MarginallyClever/makelangelofirmwareams.  So... and this is a big ask... can you either (a) move this code to that repo or (b) add AMS support to the current firmware?

**Pull request closed without merging**
